# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161009_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=b'unknown', max_length=128, unique=True),
        ),
    ]
